class PublicProductVersions {
    /**
     * Get a collection of products.
     * @param {Object} options - List of resource collection options.
     * @param {boolean} usePost - Variable to determine if the request is by 'post' or 'get' functions.
     */
    async getProductVersions(options = null, usePost = true) {
        return this.getQueryResults('/ecommerce/product-versions', options, usePost);
    }

    /**
     * Get a single product.
     * @param {string} slug - It's the string identifier generated by Mints.
     * @param {Object} options - List of single resource options.
     */
    async getProductVersion(slug, options = null) {
        return this.client.raw('get', `/ecommerce/product-versions/${slug}`, options);
    }
}

export default PublicProductVersions;