class PublicContentInstances {
    /**
     * Get Content Instances.
     * Get a collection of content instances. Note: Options must be specified.
     * @param {Object} options - List of resource collection options.
     * @returns {Promise} - A promise that resolves with the content instances data.
     * @example
     * const options = {
     *   "template": "contentInstanceTemplateSlug"
     * };
     * const data = await mintsPub.getContentInstances(options);
     */
    getContentInstances(options = null) {
        if (!options || !options.template) {
            throw new Error('Options must be specified. Example: { "template": "contentInstanceTemplateSlug" }');
        }
        return this.client.raw('get', '/content/content-instances', options);
    }

    /**
     * Get Content Instance.
     * Get a single content instance.
     * @param {string} slug - It's the string identifier generated by Mints.
     * @returns {Promise} - A promise that resolves with the content instance data.
     * @example
     * const data = await mintsPub.getContentInstance("contentInstanceSlug");
     */
    getContentInstance(slug) {
        return this.client.raw('get', `/content/content-instances/${slug}`);
    }
}

export default PublicContentInstances;