class PublicForms {
    /**
     * Get Forms.
     * Get a collection of forms.
     * @param {Object} options - List of resource collection options.
     * @returns {Promise} - A promise that resolves with the forms data.
     * @example
     * const data = await mintsPub.getForms();
     */
    getForms(options = null) {
        return this.client.raw('get', '/content/forms', options);
    }

    /**
     * Get Form.
     * Get a single form.
     * @param {string} slug - It's the string identifier generated by Mints.
     * @param {Object} options - List of single resource options.
     * @returns {Promise} - A promise that resolves with the form data.
     * @example
     * const data = await mintsPub.getForm("formSlug");
     */
    getForm(slug, options = null) {
        return this.client.raw('get', `/content/forms/${slug}`, options);
    }

    /**
     * Submit Form.
     * Submit a form with data.
     * @param {Object} data - Data to be submitted.
     * @returns {Promise} - A promise that resolves with the submitted form data.
     * @example
     * const data = {
     *   'formSlug': 'formSlug',
     *   'email': 'email@example.com',
     *   'given_name': 'given_name',
     *   'f1': 'Field 1 answer',
     *   'f2': 'Field 2 answer',
     *   'f3': 'Field 3 answer'
     * };
     * const result = await mintsPub.submitForm(data);
     */
    submitForm(data) {
        return this.client.raw('post', '/content/forms/submit', null, this.dataTransform(data));
    }
}

export default PublicForms;