class PublicStoryVersions {

    /**
     * Get Story Versions.
     * Get a collection of story version.
     *
     * @param {Object} options - List of Resource collection Options shown above can be used as parameter.
     * @param {Boolean} usePost - Variable to determine if the request is by 'post' or 'get' functions.
     * @returns {Promise} A promise that resolves to the data returned from the request.
     *
     * @example
     * const data = await PublicStoryVersions.getStoryVersions();
     *
     * @example
     * const options = {
     *   fields: 'id, title'
     * };
     * const data = await PublicStoryVersions.getStoryVersions(options);
     *
     * @example
     * const options = {
     *   fields: 'id, title'
     * };
     * const data = await PublicStoryVersions.getStoryVersions(options, false);
     */
    async getStoryVersions(options = null, usePost = true) {
        return this.client.raw(usePost ? 'post' : 'get', '/content/story-versions', options);
    }

    /**
     * Get Story Version.
     * Get a single story version.
     *
     * @param {String} slug - It's the string identifier generated by Mints.
     * @param {Object} options - List of Single Resource Options shown above can be used as parameter.
     * @returns {Promise} A promise that resolves to the data returned from the request.
     *
     * @example
     * const data = await PublicStoryVersions.getStoryVersion('storySlug');
     *
     * @example
     * const options = {
     *   fields: 'id, title'
     * };
     * const data = await PublicStoryVersions.getStoryVersion('storySlug', options);
     */
    async getStoryVersion(slug, options = null) {
        return this.client.raw('get', `/content/story-versions/${slug}`, options);
    }
}

export default PublicStoryVersions;