class PublicStories {
    /**
     * Get Stories.
     * Get a collection of stories.
     * @param {Object} options - List of resource collection options.
     * @param {boolean} usePost - Variable to determine if the request is by 'post' or 'get' functions.
     * @returns {Promise} - A promise that resolves with the stories data.
     * @example
     * const data = await mintsPub.getStories();
     */
    getStories(options = null, usePost = true) {
        return this.getQueryResults('/content/stories', options, usePost);
    }

    /**
     * Get Story.
     * Get a single story.
     * @param {string} slug - It's the string identifier generated by Mints.
     * @param {Object} options - List of single resource options.
     * @returns {Promise} - A promise that resolves with the story data.
     * @example
     * const data = await mintsPub.getStory("storySlug");
     */
    getStory(slug, options = null) {
        return this.client.raw('get', `/content/stories/${slug}`, options);
    }
}

export default PublicStories;