class PublicFolders {
    /**
     * Get Public Folders.
     * Get a collection of public folders.
     * @param {Object} options - List of Single Resource Options shown above can be used as parameter.
     * @example
     * const options = {
     *   objectType: "products"
     * };
     * const data = this.mintsPub.getPublicFolders(options);
     * @example
     * const options = {
     *   objectType: "products",
     *   fields: "id",
     *   sort: "-id"
     * };
     * const data = this.mintsPub.getPublicFolders(options);
     */
    getPublicFolders(options = null) {
        return this.client.raw('get', '/config/public-folders', options);
    }

    /**
     * Get Public Folder.
     * Get a public folder info.
     * @param {string} slug - It's the string identifier generated by Mints.
     * @param {Object} options - List of Single Resource Options shown above can be used as parameter.
     * @example
     * const options = {
     *   objectType: "products"
     * };
     * const data = this.mintsPub.getPublicFolder('yellow', options);
     * @example
     * const options = {
     *   objectType: "products",
     *   fields: 'id, title'
     * };
     * const data = this.mintsPub.getPublicFolder('yellow', options);
     */
    getPublicFolder(slug, options) {
        return this.client.raw('get', `/config/public-folders/${slug}`, options);
    }
}

export default PublicFolders;