class PublicTags {
    /**
     * Get Tags.
     * Get a collection of tags.
     * @param {Object} options - List of Resource collection Options shown above can be used as parameter.
     * @example
     * const data = this.mintsPub.getTags();
     * @example
     * const options = {
     *   fields: "id, tag"
     * };
     * const data = this.mintsPub.getTags(options);
     */
    getTags(options = null) {
        return this.client.raw('get', '/config/tags', options);
    }

    /**
     * Get Tag.
     * Get a single tag.
     * @param {string} slug - It's the string identifier generated by Mints.
     * @param {Object} options - List of Single Resource Options shown above can be used as parameter.
     * @example
     * const data = this.mintsPub.getTag("tagSlug");
     * @example
     * const options = {
     *   fields: "id, tag"
     * };
     * const data = this.mintsPub.getTag("tag-example", options);
     */
    getTag(slug, options = null) {
        return this.client.raw('get', `/config/tags/${slug}`, options);
    }
}

export default PublicTags;