class PublicTaxonomies {
    /**
     * Get Taxonomies.
     * Get a collection of taxonomies.
     * @param {Object} options - List of Resource collection Options shown above can be used as parameter.
     * @param {boolean} usePost - Variable to determine if the request is by 'post' or 'get' functions.
     * @example
     * const data = this.mintsPub.getTaxonomies();
     * @example
     * const options = {
     *   fields: 'id, title'
     * };
     * const data = this.mintsPub.getTaxonomies(options);
     * @example
     * const options = {
     *   fields: 'id, title'
     * };
     * const data = this.mintsPub.getTaxonomies(options, false);
     */
    getTaxonomies(options = null, usePost = true) {
        return this.getQueryResults('/config/taxonomies', options, usePost);
    }

    /**
     * Get Taxonomy.
     * Get a single taxonomy.
     * @param {string} slug - It's the string identifier generated by Mints.
     * @param {Object} options - List of Single Resource Options shown above can be used as parameter.
     * @example
     * const data = this.mintsPub.getTaxonomy('taxonomySlug');
     * @example
     * const options = {
     *   fields: 'title'
     * };
     * const data = this.mintsPub.getTaxonomy('taxonomySlug', options);
     */
    getTaxonomy(slug, options = null) {
        return this.client.raw('get', `/config/taxonomies/${slug}`, options);
    }
}

export default PublicTaxonomies;
